import type { Metadata } from 'next';
import { ReactNode } from 'react';

import { LineSeedKR } from '@/styles/font';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'WOODAE FOLIO',
  description: 'Generated by Daehyun woo F/E developer'
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
      </head>
      <body>
        <main className={`${LineSeedKR.variable} app-layout font-lineseed`}>
          {children}
        </main>
      </body>
    </html>
  );
}
