import type { Metadata } from 'next';
import { ReactNode } from 'react';

import { LineSeedKR } from '@/styles/font';
import '@/styles/globals.css';

export const metadata: Metadata = {
  title: 'WOODAE FOLIO',
  description: 'Generated by Daehyun woo F/E developer'
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="ko">
      <body className="app-layout">
        <main className={`${LineSeedKR.variable} font-lineseed `}>
          {children}
        </main>
      </body>
    </html>
  );
}
